### ISSUE TITLE
Crash when using a resolver with ivy style patterns

### ISSUE THREAD

**Issue by kaharlichenko** [scalacenter/sbt-version-policy#127]
Adding a resolver that uses ivy style patters to `build.sbt` makes sbt crash when reading the project definition.

Below are the steps to reproduce the issue:

```sh
sbt new scala/scala-seed.g8 --name=bug --branch=2.13.x

cd bug

echo "sbt.version=1.6.2" > project/build.properties

cat <<EOF >> project/plugins.sbt
addSbtPlugin("ch.epfl.scala" % "sbt-version-policy" % "2.0.1")
EOF

cat <<EOF >> build.sbt
ThisBuild / resolvers += Resolver.typesafeIvyRepo("releases")
EOF

echo "ThisBuild / versionPolicyIntention := Compatibility.None" > versionPolicy.sbt

sbt compile
```

This leads to the error shown below:

<details><summary>Stack Trace</summary>

```
[info] welcome to sbt 1.6.2 (Oracle Corporation Java 11.0.11)
[info] loading settings for project global-plugins from plugins.sbt ...
[info] loading global plugins from /home/username/.sbt/1.0/plugins
[info] loading settings for project bug-build from plugins.sbt ...
[info] loading project definition from /tmp/bug/project
[info] loading settings for project root from build.sbt,versionPolicy.sbt ...
java.net.MalformedURLException: URL ivy:https://repo.typesafe.com/typesafe/ivy-releases/[organisation]/[module]/(scala_[scalaVersion]/)(sbt_[sbtVersion]/)([branch]/)[revision]/[type]s/[artifact](-[classifier]).[ext]|https://repo.typesafe.com/typesafe/ivy-releases/[organisation]/[module]/(scala_[scalaVersion]/)(sbt_[sbtVersion]/)([branch]/)[revision]/[type]s/[artifact](-[classifier]).[ext]/com/example/bug_2.13/maven-metadata.xml doesn't contain an absolute path
	at coursierapi.shaded.coursier.paths.CachePath.localFile(CachePath.java:74)
	at coursierapi.shaded.coursier.cache.FileCache$.localFile0(FileCache.scala:367)
	at coursierapi.shaded.coursier.cache.internal.Downloader.localFile(Downloader.scala:50)
	at coursierapi.shaded.coursier.cache.internal.Downloader.downloadUrl(Downloader.scala:540)
	at coursierapi.shaded.coursier.cache.internal.Downloader.download(Downloader.scala:605)
	at coursierapi.shaded.coursier.cache.FileCache.download(FileCache.scala:85)
	at coursierapi.shaded.coursier.cache.FileCache.filePerPolicy0(FileCache.scala:178)
	at coursierapi.shaded.coursier.cache.FileCache.$anonfun$filePerPolicy$5(FileCache.scala:165)
	at coursierapi.shaded.coursier.util.EitherT.$anonfun$flatMap$1(EitherT.scala:18)
	at coursierapi.shaded.coursier.util.Task$.$anonfun$flatMap$extension$1(Task.scala:14)
	at coursierapi.shaded.coursier.util.Task$.$anonfun$flatMap$extension$1$adapted(Task.scala:14)
	at coursierapi.shaded.coursier.util.Task$.wrap(Task.scala:84)
	at coursierapi.shaded.coursier.util.Task$.$anonfun$flatMap$2(Task.scala:14)
	at coursierapi.shaded.scala.concurrent.impl.Promise$Transformation.run(Promise.scala:433)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
[error] java.net.MalformedURLException: URL ivy:https://repo.typesafe.com/typesafe/ivy-releases/[organisation]/[module]/(scala_[scalaVersion]/)(sbt_[sbtVersion]/)([branch]/)[revision]/[type]s/[artifact](-[classifier]).[ext]|https://repo.typesafe.com/typesafe/ivy-releases/[organisation]/[module]/(scala_[scalaVersion]/)(sbt_[sbtVersion]/)([branch]/)[revision]/[type]s/[artifact](-[classifier]).[ext]/com/example/bug_2.13/maven-metadata.xml doesn't contain an absolute path
[error] Use 'last' for the full log.
[warn] Project loading failed: (r)etry, (q)uit, (l)ast, or (i)gnore? (default: r)
```
</details>

**Comment by alexarchambault** [comment]
That looks like an oversight in [this method](https://github.com/scalacenter/sbt-version-policy/blob/1a705db0166792995fb43dfe2e666a00df111455/sbt-version-policy/src/main/scala/sbtversionpolicy/internal/Resolvers.scala#L59-L92). I think it lacks a case or a condition to handle non-file based Ivy repos.
